/*
 * aether.c — Bootstrap compiler CLI.
 * Reads .ae files, tokenizes, parses, analyzes, generates NASM,
 * assembles with nasm, and links with ld (freestanding ELF64)
 * or clang (Mach-O 64 for macOS).
 *
 * Also supports:
 *   aether init <name>   — scaffold a new project
 *   aether.toml          — project manifest discovery
 *   --linker-script      — custom linker script
 *   New targets: kernel, module, binary, boot
 */

#include "aether/tokenizer.h"
#include "aether/lexer.h"
#include "aether/ast.h"
#include "aether/parser.h"
#include "aether/semantic.h"
#include "aether/codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>

static void usage(const char *prog) {
    fprintf(stderr, "Aether Compiler v0.3 (Phase 6 — OS Integration)\n");
    fprintf(stderr, "Usage:\n");
    fprintf(stderr, "  %s [options] <file.ae>\n", prog);
    fprintf(stderr, "  %s init|new <project-name>\n", prog);
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -o, --output <file>      Output file (default: a.out)\n");
    fprintf(stderr, "  --target <target>        Output target:\n");
    fprintf(stderr, "    host                   Auto-detect host format (default)\n");
    fprintf(stderr, "    x86_64-freestanding    Aether OS ELF64\n");
    fprintf(stderr, "    macho64                Mach-O 64 (macOS)\n");
    fprintf(stderr, "    elf64-host             Native ELF64 (Linux)\n");
    fprintf(stderr, "    kernel                 Kernel ELF at 0x1000000\n");
    fprintf(stderr, "    module                 Aether OS .ko module\n");
    fprintf(stderr, "    binary                 /bin/ userland ELF at 0x2000000\n");
    fprintf(stderr, "    boot                   Flat binary boot sector\n");
    fprintf(stderr, "  -L, --linker-script <f>  Custom linker script\n");
    fprintf(stderr, "  -S                       Stop after assembly (emit .asm)\n");
    fprintf(stderr, "  --dump-ast               Print AST and exit\n");
    fprintf(stderr, "  --dump-tokens            Print tokens and exit\n");
    fprintf(stderr, "  -v, --verbose            Verbose output\n");
}

/* Create directory (mkdir -p equivalent) */
static int mkdir_p(const char *path) {
    char tmp[1024];
    size_t len = strlen(path);
    if (len > sizeof(tmp) - 1) return -1;
    memcpy(tmp, path, len + 1);
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            mkdir(tmp, 0755);
            *p = '/';
        }
    }
    return mkdir(tmp, 0755);
}

/* Scaffold a new project: aether init <name> */
static int cmd_init(const char *prog, const char *name) {
    (void)prog;
    char dir[1024];
    char path[2048];

    snprintf(dir, sizeof(dir), "%s", name);
    if (mkdir_p(dir) != 0 && errno != EEXIST) {
        fprintf(stderr, "Error: cannot create directory '%s'\n", dir);
        return 1;
    }

    /* Create src/ */
    snprintf(path, sizeof(path), "%s/src", dir);
    mkdir(path, 0755);

    /* Create tests/ */
    snprintf(path, sizeof(path), "%s/tests", dir);
    mkdir(path, 0755);

    /* Create aether.toml */
    snprintf(path, sizeof(path), "%s/aether.toml", dir);
    FILE *f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "Error: cannot create '%s'\n", path);
        return 1;
    }
    fprintf(f, "[project]\n");
    fprintf(f, "name = \"%s\"\n", name);
    fprintf(f, "version = \"0.1.0\"\n");
    fprintf(f, "\n");
    fprintf(f, "[build]\n");
    fprintf(f, "target = \"host\"\n");
    fprintf(f, "output = \"%s\"\n", name);
    fprintf(f, "# linker-script = \"link.ld\"\n");
    fclose(f);

    /* Create src/main.ae */
    snprintf(path, sizeof(path), "%s/src/main.ae", dir);
    f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "Error: cannot create '%s'\n", path);
        return 1;
    }
    fprintf(f, "# %s — Aether project\n", name);
    fprintf(f, "# Generated by `aether init`\n\n");
    fprintf(f, "func main(): u64 {\n");
    fprintf(f, "    print(\"Hello from Aether!\\n\")\n");
    fprintf(f, "    return 0\n");
    fprintf(f, "}\n");
    fclose(f);

    printf("Created project '%s' at %s/\n", name, dir);
    printf("  %s/aether.toml\n", dir);
    printf("  %s/src/main.ae\n", dir);
    printf("  %s/tests/\n", dir);
    printf("\n");
    printf("To build: cd %s && aether src/main.ae\n", dir);
    return 0;
}

/* Simple TOML-like parsing: read a file line by line, extract key = value */
/* Returns 0 on success, -1 on error. */
/* Supported keys: target, output, linker-script (under [build] section) */
static int parse_aether_toml(const char *path,
                             char *target_out, size_t target_sz,
                             char *output_out, size_t output_sz,
                             char *linker_script_out, size_t linker_sz)
{
    FILE *f = fopen(path, "r");
    if (!f) return -1;

    int in_build_section = 0;
    char line[512];
    int ret = 0;

    while (fgets(line, sizeof(line), f)) {
        /* Strip trailing newline */
        size_t len = strlen(line);
        while (len > 0 && (line[len-1] == '\n' || line[len-1] == '\r'))
            line[--len] = '\0';

        /* Skip blank and comment lines */
        const char *p = line;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == '\0' || *p == '#') continue;

        /* Section headers */
        if (*p == '[') {
            in_build_section = (strcmp(p, "[build]") == 0);
            continue;
        }

        if (!in_build_section) continue;

        /* Parse key = value */
        const char *eq = strchr(p, '=');
        if (!eq) continue;

        char key[128];
        int klen = (int)(size_t)(eq - p);
        /* Trim trailing spaces from key */
        while (klen > 0 && (p[klen-1] == ' ' || p[klen-1] == '\t')) klen--;
        if (klen > 127) klen = 127;
        memcpy(key, p, klen);
        key[klen] = '\0';

        /* Skip spaces after = */
        const char *val = eq + 1;
        while (*val == ' ' || *val == '\t') val++;

        /* Strip surrounding quotes */
        const char *vstart = val;
        size_t vlen = strlen(val);
        if (vlen > 1 && val[0] == '"' && val[vlen-1] == '"') {
            vstart = val + 1;
            vlen = vlen - 2;
        }

        if (strcmp(key, "target") == 0) {
            size_t copy = vlen < target_sz - 1 ? vlen : target_sz - 1;
            memcpy(target_out, vstart, copy);
            target_out[copy] = '\0';
        } else if (strcmp(key, "output") == 0) {
            size_t copy = vlen < output_sz - 1 ? vlen : output_sz - 1;
            memcpy(output_out, vstart, copy);
            output_out[copy] = '\0';
        } else if (strcmp(key, "linker-script") == 0 || strcmp(key, "linker_script") == 0) {
            size_t copy = vlen < linker_sz - 1 ? vlen : linker_sz - 1;
            memcpy(linker_script_out, vstart, copy);
            linker_script_out[copy] = '\0';
        }
    }

    fclose(f);
    return ret;
}

/* Map a string target name to Target enum */
/* Returns -1 on unknown target */
static int parse_target_name(const char *t) {
    if (strcmp(t, "host") == 0)               return (int)TARGET_HOST;
    if (strcmp(t, "x86_64-freestanding") == 0) return (int)TARGET_FREESTANDING;
    if (strcmp(t, "macho64") == 0)             return (int)TARGET_MACHO64;
    if (strcmp(t, "elf64-host") == 0)          return (int)TARGET_ELF64_HOST;
    if (strcmp(t, "kernel") == 0)              return (int)TARGET_KERNEL;
    if (strcmp(t, "module") == 0)              return (int)TARGET_MODULE;
    if (strcmp(t, "binary") == 0)              return (int)TARGET_BINARY;
    if (strcmp(t, "boot") == 0)                return (int)TARGET_BOOT;
    return -1;
}

/* Return true if the file exists */
static int file_exists(const char *path) {
    FILE *f = fopen(path, "r");
    if (f) { fclose(f); return 1; }
    return 0;
}

int main(int argc, char **argv) {
    const char *input_file = NULL;
    const char *output_file = NULL;
    int stop_after_asm = 0;
    int dump_ast = 0;
    int dump_tokens = 0;
    int verbose = 0;
    int run_mode = 0;
    Target target = TARGET_HOST; /* default: auto-detect */
    const char *linker_script = NULL;

    /* Check for subcommands: init, new, run */
    if (argc > 1) {
        if (strcmp(argv[1], "init") == 0 || strcmp(argv[1], "new") == 0) {
            if (argc < 3) {
                fprintf(stderr, "Error: 'init' requires a project name\n");
                usage(argv[0]);
                return 1;
            }
            return cmd_init(argv[0], argv[2]);
        }
        if (strcmp(argv[1], "run") == 0) {
            run_mode = 1;
        }
    }

    /* Parse args */
    int argi = (run_mode) ? 2 : 1;
    for (int i = argi; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0) {
            if (i + 1 < argc) output_file = argv[++i];
        } else if (strcmp(argv[i], "--target") == 0) {
            if (i + 1 < argc) {
                const char *t = argv[++i];
                int parsed = parse_target_name(t);
                if (parsed < 0) {
                    fprintf(stderr, "Unknown target: %s\n", t);
                    usage(argv[0]);
                    return 1;
                }
                target = (Target)parsed;
            }
        } else if (strcmp(argv[i], "-L") == 0 || strcmp(argv[i], "--linker-script") == 0) {
            if (i + 1 < argc) linker_script = argv[++i];
        } else if (strcmp(argv[i], "-S") == 0) {
            stop_after_asm = 1;
        } else if (strcmp(argv[i], "--dump-ast") == 0) {
            dump_ast = 1;
        } else if (strcmp(argv[i], "--dump-tokens") == 0) {
            dump_tokens = 1;
        } else if (strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--verbose") == 0) {
            verbose = 1;
        } else if (argv[i][0] != '-') {
            input_file = argv[i];
        } else {
            fprintf(stderr, "Unknown option: %s\n", argv[i]);
            usage(argv[0]);
            return 1;
        }
    }

    /* If no input file, check for aether.toml in cwd */
    if (!input_file) {
        if (file_exists("aether.toml")) {
            char toml_target[256] = {0};
            char toml_output[256] = {0};
            char toml_linker[256] = {0};
            if (parse_aether_toml("aether.toml", toml_target, sizeof(toml_target),
                                  toml_output, sizeof(toml_output),
                                  toml_linker, sizeof(toml_linker)) == 0)
            {
                if (toml_target[0]) {
                    int p = parse_target_name(toml_target);
                    if (p >= 0) target = (Target)p;
                    if (verbose) printf("aether.toml: target = %s\n", toml_target);
                }
                if (toml_output[0] && !output_file) {
                    char *dup = (char *)malloc(strlen(toml_output) + 1);
                    if (dup) { memcpy(dup, toml_output, strlen(toml_output) + 1); output_file = dup; }
                    if (verbose) printf("aether.toml: output = %s\n", toml_output);
                }
                if (toml_linker[0] && !linker_script) {
                    char *dup = (char *)malloc(strlen(toml_linker) + 1);
                    if (dup) { memcpy(dup, toml_linker, strlen(toml_linker) + 1); linker_script = dup; }
                    if (verbose) printf("aether.toml: linker-script = %s\n", toml_linker);
                }
            }
            fprintf(stderr, "Error: aether.toml found but no .ae file specified on command line\n");
            usage(argv[0]);
            return 1;
        }
        fprintf(stderr, "Error: no input file specified\n");
        usage(argv[0]);
        return 1;
    }

    /* Default output name */
    if (!output_file) {
        if (target == TARGET_HOST || target == TARGET_MACHO64 || target == TARGET_ELF64_HOST) {
            /* Write to /tmp/ so binaries don't pollute source tree */
            const char *fname = strrchr(input_file, '/');
            fname = fname ? fname + 1 : input_file;
            const char *dot = strrchr(fname, '.');
            if (dot && strcmp(dot, ".ae") == 0) {
                size_t base_len = (size_t)(dot - fname);
                char buf[1024];
                int n = snprintf(buf, sizeof(buf), "/tmp/%.*s", (int)base_len, fname);
                if (n > 0 && n < (int)sizeof(buf)) {
                    output_file = (const char *)malloc((size_t)n + 1);
                    if (output_file) memcpy((char *)output_file, buf, (size_t)n + 1);
                }
            } else {
                output_file = "/tmp/aether.out";
            }
        } else {
            output_file = "a.out";
        }
    }

    /* Read input file */
    FILE *f = fopen(input_file, "rb");
    if (!f) {
        fprintf(stderr, "Error: cannot open '%s'\n", input_file);
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long file_len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *source = (char *)malloc((size_t)file_len + 1);
    if (!source) { fclose(f); return 1; }
    size_t read_len = fread(source, 1, (size_t)file_len, f);
    source[read_len] = '\0';
    fclose(f);

    /* Phase 1: Tokenize */
    if (dump_tokens) {
        Tokenizer *t = tokenizer_create(source, read_len, input_file);
        int i = 0;
        while (1) {
            Token tok = tokenizer_next(t);
            printf("%3d: [%-12s] '%.*s'", i, token_type_name(tok.type),
                   (int)tok.text.len, tok.text.data);
            if (tok.type == TOKEN_INT_LITERAL)
                printf(" val=%llu", (unsigned long long)tok.val.int_value);
            if (tok.type == TOKEN_FLOAT_LITERAL)
                printf(" val=%f", tok.val.float_value);
            printf("\n");
            i++;
            if (tok.type == TOKEN_EOF) break;
            if (tok.type == TOKEN_ERROR) {
                printf("  ERROR: %.*s\n", (int)tok.text.len, tok.text.data);
                tokenizer_destroy(t);
                free(source);
                return 1;
            }
        }
        tokenizer_destroy(t);
        free(source);
        return 0;
    }

    /* Phase 2: Parse */
    Parser *parser = parser_create(source, read_len, input_file);
    AstNode *program = parser_parse(parser);

    if (parser->error_count > 0) {
        fprintf(stderr, "Parse failed with %d errors\n", parser->error_count);
        ast_dump(program, 0);
        parser_destroy(parser);
        free(source);
        return 1;
    }

    if (dump_ast) {
        printf("=== AST ===\n");
        ast_dump(program, 0);
        parser_destroy(parser);
        free(source);
        return 0;
    }

    if (verbose) {
        printf("Parse OK (%d top-level decls)\n", program->data.list.count);
    }

    /* Phase 3: Semantic analysis */
    Arena *sa_arena = arena_create();
    SemanticAnalyzer *sa = semantic_create(sa_arena);
    semantic_analyze(sa, program);
    if (sa->error_count > 0) {
        fprintf(stderr, "Semantic analysis failed with %d errors\n", sa->error_count);
        parser_destroy(parser);
        free(source);
        arena_destroy(sa_arena);
        return 1;
    }

    /* Phase 4: Code generation */
    Arena *cg_arena = arena_create();
    Codegen *cg = codegen_create(cg_arena);
    codegen_set_target(cg, target);
    cg->linker_script = linker_script;
    codegen_generate(cg, program);

    if (verbose) {
        printf("Target: %s\n", target_name(cg->target));
    }

    /* Determine output filenames */
    char asm_file[1024];

    if (stop_after_asm) {
        snprintf(asm_file, sizeof(asm_file), "%s", output_file);
    } else {
        /* Use /tmp/ for intermediate files */
        unsigned long hash = 5381;
        for (const char *p = input_file; *p; p++)
            hash = ((hash << 5) + hash) + (unsigned char)*p;
        snprintf(asm_file, sizeof(asm_file), "/tmp/aether_%lx.asm", hash);
    }

    /* Write .asm file */
    if (codegen_write_asm(cg, asm_file) != 0) {
        fprintf(stderr, "Error: cannot write '%s'\n", asm_file);
        parser_destroy(parser);
        free(source);
        arena_destroy(sa_arena);
        arena_destroy(cg_arena);
        return 1;
    }

    if (verbose) printf("Wrote %s\n", asm_file);

    if (stop_after_asm) {
        if (verbose) printf("Stopping after assembly (-S flag)\n");
        parser_destroy(parser);
        free(source);
        arena_destroy(sa_arena);
        arena_destroy(cg_arena);
        return 0;
    }

    /* Phase 5: Assemble and link */
    int ret = codegen_assemble(cg, asm_file, output_file);
    if (ret != 0) {
        fprintf(stderr, "Assembly/link failed\n");
        parser_destroy(parser);
        free(source);
        arena_destroy(sa_arena);
        arena_destroy(cg_arena);
        return 1;
    }

    if (verbose) printf("Wrote %s\n", output_file);

    /* Cleanup temp files */
    remove(asm_file);

    parser_destroy(parser);
    free(source);
    arena_destroy(sa_arena);
    arena_destroy(cg_arena);

    printf("Compilation successful: %s -> %s\n", input_file, output_file);

    if (run_mode) {
        if (verbose) printf("Running: %s\n", output_file);
        char cmd[4096];
        snprintf(cmd, sizeof(cmd), "%s", output_file);
        int ret = system(cmd);
        if (ret != 0) {
            fprintf(stderr, "Program exited with code %d\n", ret);
        }
        return ret;
    }

    return 0;
}